/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_et_testndk_NativeClass */

#ifndef _Included_com_et_testndk_NativeClass
#define _Included_com_et_testndk_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_et_testndk_NativeClass
 * Method:    getResult
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_et_testndk_NativeClass_getResult
  (JNIEnv *env, jobject);

/*
 * Class:     com_et_testndk_NativeClass
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_et_testndk_NativeClass_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
